services:
  - type: web
    name: syncflick-api
    env: docker
    dockerfilePath: ./Dockerfile
    dockerContext: .
    envVars:
      - key: CORS_ORIGINS
        sync: false
      - key: VIDEOS_DIR
        value: /tmp/videos
      - key: MAX_FILE_SIZE_MB
        value: "2048"
